apiVersion: v1
kind: Secret
metadata:
  name: alertmanager-smtp
  namespace: monitoring
type: Opaque
stringData:
  smtp_smarthost: "smtp.office365.com:587"
  smtp_from: "wallaces098@hotmail.com"
  smtp_auth_username: "wallaces098@hotmail.com"
  smtp_auth_password: "usqaxaxdzrlpdvmo"

